import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { resolve, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const DOCS_ROOT = resolve(__dirname, '../../../apps/docs/docs')
const COMPONENTS_DIR = resolve(DOCS_ROOT, 'components')
const NEXT_DIR = resolve(DOCS_ROOT, 'next')
const OUT_DIR = resolve(__dirname, '../src/generated')

/** MDX → clean markdown (코드블록 외부 import/JSX/directives 제거) */
function mdxToMarkdown(content) {
  const lines = content.split('\n')
  const result = []
  let inCodeBlock = false

  for (const line of lines) {
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock
      result.push(line)
      continue
    }
    if (inCodeBlock) {
      result.push(line)
      continue
    }
    if (line.startsWith('import ')) continue
    if (/<[A-Z][A-Za-z]+[^>]*\/>/.test(line)) continue
    if (/^:::/.test(line)) {
      result.push('')
      continue
    }
    result.push(line)
  }

  return result.join('\n').replace(/\n{3,}/g, '\n\n').trim()
}

function extractTitle(content) {
  const match = content.match(/^# (.+)$/m)
  return match ? match[1].trim() : ''
}

function extractDescription(content) {
  const lines = content.split('\n')
  let foundH1 = false
  let inCodeBlock = false
  for (const line of lines) {
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock
      continue
    }
    if (inCodeBlock) continue
    if (line.startsWith('# ')) {
      foundH1 = true
      continue
    }
    if (!foundH1) continue
    const trimmed = line.trim()
    if (
      trimmed &&
      !trimmed.startsWith('#') &&
      !trimmed.startsWith('import ') &&
      !trimmed.startsWith(':::') &&
      !trimmed.startsWith('<') &&
      !trimmed.startsWith('|') &&
      !trimmed.startsWith('`') &&
      !trimmed.startsWith('```') &&
      !trimmed.startsWith('//')
    ) {
      return trimmed.length > 120 ? `${trimmed.slice(0, 117)}...` : trimmed
    }
  }
  return ''
}

function readComponents(sourceDir, platform, entry) {
  return readdirSync(sourceDir)
    .filter((f) => f.endsWith('.mdx'))
    .map((file) => {
      const slug = basename(file, '.mdx')
      const raw = readFileSync(resolve(sourceDir, file), 'utf-8')
      return {
        slug,
        title: extractTitle(raw),
        description: extractDescription(raw),
        platform,
        entry,
        content: mdxToMarkdown(raw),
      }
    })
}

const components = [
  ...readComponents(COMPONENTS_DIR, 'web', '@coldsurf/ocean-road'),
  ...readComponents(NEXT_DIR, 'next', '@coldsurf/ocean-road/next'),
]

mkdirSync(OUT_DIR, { recursive: true })

const ts = `// @ts-nocheck
// DO NOT EDIT — auto-generated by scripts/generate-data.mjs

export interface ComponentEntry {
  slug: string
  title: string
  description: string
  platform: 'web' | 'next'
  entry: string
  content: string
}

export const components: ComponentEntry[] = ${JSON.stringify(components, null, 2)}
`

writeFileSync(resolve(OUT_DIR, 'data.ts'), ts, 'utf-8')
console.log(`✅ Generated src/generated/data.ts (${components.length} components)`)
